///Get games
export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'
export const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME'
///Post Game
export const POST_VIDEOGAME = 'POST_VIDEOGAME'
///Filters
export const GET_VIDEOGAME_SOURCE = 'GET_VIDEOGAME_SOURCE'
export const GET_VIDEOGAME_BY_GENRE = 'GET_VIDEOGAME_BY_GENRE'
export const ORDER_VIDEOGAME_BY_NAME = 'ORDER_VIDEOGAME_BY_NAME'
export const ORDER_VIDEOGAME_BY_RATING = 'ORDER_VIDEOGAME_BY_RATING'
export const GET_VIDEOGAME_BY_PLATFORM = 'GET_VIDEOGAME_BY_PLATFORM'
///Get Genres
export const GET_ALL_GENRES = 'GET_ALL_GENRES'
///Reset Videogames
export const RESET_VIDEOGAMES = "RESET_VIDEOGAMES"
export const RESET_VIDEOGAMES_SEARCHED = "RESET_VIDEOGAMES_SEARCHED"
///Handle Paginate
export const HANDLE_NUMBER = 'HANDLE_NUMBER'
export const NEXT_PAGE = "NEXT_PAGE"
export const PREV_PAGE = "PREV_PAGE"

